version: '3.8'

services:
  php:
    build:
      context: .
    container_name: php_container
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
      - ./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    depends_on:
      - php

  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: rat
      MYSQL_PASSWORD: rat
      MYSQL_ROOT_PASSWORD: rat
    ports:
      - "3306:3306"
    volumes:
      # - ./mysql/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - 8090:8080

volumes:
  mysql_data:
